### ISSUE TITLE
Bug: Emote Modifier issues in Firefox

### ISSUE THREAD

**Issue by Shugabuga** [Rothera/bpm#16]
Firefox (Mac) is having some issues, especially with Chaos modifiers like `-slide!`. The issue is shown below.

**Chrome Canary: Everything is working as expected.**
<img width="484" alt="chrome_canary" src="https://cloud.githubusercontent.com/assets/10801851/14968756/97a0537c-108c-11e6-95b5-1ef6fabb55a4.png">
**Normal Firefox: -slide! doesn't work as expected, everything else OK.**
<img width="483" alt="firefox_normal" src="https://cloud.githubusercontent.com/assets/10801851/14968753/979f7f92-108c-11e6-9fbe-71c9ee51c77e.png">
**Firefox Developer: -slide, -slide!, and other keyframe-based Chaos "modifiers" don't work.**
<img width="387" alt="firefox_dev" src="https://cloud.githubusercontent.com/assets/10801851/14968754/979fec84-108c-11e6-8d39-5b8e18185733.png">
**Firefox Nightly: Same errors as Developer Edition, but with the emote name exposed. Also, the spritesheet seems broken.**
<img width="435" alt="firefox_night" src="https://cloud.githubusercontent.com/assets/10801851/14968755/97a0269a-108c-11e6-95bd-f65e3c89eb1c.png">
**Firefox Nightly: Clicking on the emote twice seems to remove the exposed name, but that's it.**
<img width="428" alt="firefox_night_afterclickall" src="https://cloud.githubusercontent.com/assets/10801851/14968792/c6a932ec-108c-11e6-9143-ef392acc5141.png">

**This isn't specific to any emotes, as seen below (in Firefox Nightly):**
<img width="357" alt="firefox_nightly_wtf" src="https://cloud.githubusercontent.com/assets/10801851/14968757/97a142aa-108c-11e6-864e-cce637e520c2.png">

This page can be viewed at [https://goo.gl/0XLVjK.](https://goo.gl/0XLVjK)

Also, "the Works/Doesn't" Work refers to the animation in Firefox Developer.

[Imgur Link](http://imgur.com/a/s7Rhi)

**Using BPM version 66.244.mozsucks**

**Comment by Rothera** [comment]
I think I fixed the !slide thing real quick, but I'm leaving the nightly fun for later.

**Comment by Shugabuga** [comment]
I also found a fix that works on my machine running Mac OS X 10.11.4. Commited to my pull request.
