### ISSUE TITLE
-m flag doesn't work in Desktop plugin

### ISSUE THREAD

**Issue by TallonRain** [Rothera/bpm#18]
As title states and as previously demonstrated to Chal, the -m flag doesn't trigger for emotes to which it applies in the Desktop client plugin. 
![image](https://cloud.githubusercontent.com/assets/4109831/15455489/2f941e00-201b-11e6-9712-fc38caa5f5b1.png)
 `[](/twibeam-m)` is demonstrated above

**Comment by Rothera** [comment]
I'm not sure what the desktop client is. Where is this?

**Comment by Rothera** [comment]
If it's anything other than reddit than I think I know about it (`-m` was not implemented the same was as everything else) but that should be working in v66.245.

**Comment by Shugabuga** [comment]
If you're talking about BPM for Discord, it's because of how the `-m` flag was implemented in versions 66.244 and earlier, as Typhos stated. As soon as ByzantineFailure updates BPM for Discord, the problem should be solved.

**Comment by ByzantineFailure** [comment]
Issue filed in the wrong repo -- feel free to close, I will reopen on my fork.

**Comment by TallonRain** [comment]
As @ByzantineFailure stated, apparently it was the wrong repo. Apologies.
