### ISSUE TITLE
Certain emotes don't work properly.

### ISSUE THREAD

**Issue by Shugabuga** [Rothera/bpm#20]
**The following emotes do not work on Google Chrome (both Canary and Stable), but work on Firefox and Safari:**

\[](/adagiopoweredup)

\[](/adagiosmug)

\[](/sirenadagio)

\[](/ariapoweredup)

\[](/ariagrumpy)

\[](/sirenaria)

\[](/sirensonata)

\[](/sonatapoweredup)

**The following emotes are supposed to be animated (they are in their home sub) but aren't in BPM (all browsers):**

\[](/fsnom)

\[](/pattycake)

For the animotes, maybe it could be because the use of `@keyframes` and CSS animations causing the issue?

For the other ones, they all do seem like they are in a set and don't work on their home subreddit, so I will contact the owners of the subreddits to try and fix this, but I will keep them here for documentation purposes.

**Images (from [this comment](https://www.reddit.com/r/heyitsshugatest/comments/4hjrt5/bpm_bug_found_certain_modifiers_wont_work_in/d4mee5r):**

![Firefox Preview](https://cloud.githubusercontent.com/assets/10801851/16343773/0f703c66-3a07-11e6-85b5-f37c1f348664.png)
![Chrome Preview](https://cloud.githubusercontent.com/assets/10801851/16343772/0f6dd73c-3a07-11e6-8992-1da5ebbb248a.png)

**Comment by nano23823** [comment]
Reddit only allows JPG or PNG uploads for the stylesheet. So if we want animated emotes, either APNGs or CSS must be used. BPM, however, does not support CSS animations, and Chrome [does not support APNG images](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/KcMjmFOgG2w). While there is an [extension](https://chrome.google.com/webstore/detail/apng/ehkepjiconegkhpodgoaeamnpckdbblp?hl=en), it only works for direct images or on inline styles, and thus not our emotes. BPM's solution for this is to host converted GIF versions of APNG emotes on [ponymotes.net](ponymotes.net).

Inspect one of the emotes in question with Chrome to obtain the URL of the GIF version. If you try to load this, you will see they are all giving 403 errors. Presumably they have incorrect permissions on the ponymotes server.

**Comment by Rothera** [comment]
The first group is due to me forgetting to set correct permissions on some files, causing nginx to be unable to serve the GIF versions for Chrome. Since I've done this a couple times already and I am, in theory, a programmer skilled at making my computer solve my problems for me, I have hopefully fixed this somewhat more permanently.

As noted, BPM does not support CSS animations. This is somewhat unfortunate as some subreddits like to use them so that they work in Chrome.

**Comment by Shugabuga** [comment]
So, just use APNGs?

**Comment by Rothera** [comment]
Pretty much. I think /r/sunsetshimmer uses both styles, with the CSS version ignored.

**Comment by Shugabuga** [comment]
[](/ppthumbsup) Ok. I'll contact the owner of the fluttermotes and we'll fix it.

**Comment by Shugabuga** [comment]
/r/adagiodazzle, /r/ariablaze, and /r/sonatadusk have been fixed on my end BTW. Thanks!
