### ISSUE TITLE
[Bug] Some emotes aren't searchable

### ISSUE THREAD

**Issue by Shugabuga** [Rothera/bpm#27]
Some emotes, like `[](/twifrisk)`, don't appear in BPM's search box, They seem to be tagged and "coded in" properly, yet don't exist in the searchbox (works when typed in manually though).

**Comment by Shugabuga** [comment]
And I forgot the +nonpony tag. Closing...

**Comment by Rothera** [comment]
Tee hee.

Upon reflection, will remove that tag. Not consistent with the usual rules for it.
