### ISSUE TITLE
Support Firefox multiprocess

### ISSUE THREAD

**Issue by Jibodeah** [Rothera/bpm#35]
I know we had a pull (#31) for this already, but the addon still isn't marked as multiprocess compatible. If you install Mozilla's [Add-on Compatibility Reporter](https://addons.mozilla.org/en-GB/firefox/addon/add-on-compatibility-reporter/) it flags BPM as not compatible, like so:

![](https://cloud.githubusercontent.com/assets/1408692/20265383/a5807898-aa68-11e6-9278-131295313bbb.png)

I'm pretty sure the reason is the lack of the [multiprocessCompatible](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#multiprocessCompatible) property in the [install.rdf](https://github.com/Rothera/bpm/blob/master/addon/fx-install.rdf). So the fix is probably as simple as just adding that and checking everything still works.

Note: [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) are fully compatible with multiprocess, as well as being the preferred way of doing extensions in Firefox. Possibly should think of doing the Firefox addon that way.

**Comment by Shugabuga** [comment]
Well crap. I thought #31 would fix it. Thanks for re-opening the issue and bringing this to my attention. I'll fix this soon (hopefully) using the `install.rdf` method.

Plus, it may be easier in the long run (especially for @Rothera and I since Firefox is a pain) to make the plunge to WebExtensions, but I want to wait until I finish some auto-update stuff, which will be a while.

**Comment by Jibodeah** [comment]
Forgive me I've got the wrong idea, but isn't the Chrome version a WebExtension anyway? So one would assume that it'd be reasonably simple. You'd just have to make both Chrome and Firefox use the WebExtension version, altering it so that any browser specific stuff (like the workaround for Chrome's lack of APNG support) only runs in that browser.

**Comment by Shugabuga** [comment]
>  but isn't the Chrome version a WebExtension anyway?

**Pretty much.** WebExtensions are pretty much designed to be compatible with Chrome IIRC. I don't see it being too difficult for either Typhos or I to deal with, but I'm currently working on the aforementioned auto-update code, so I can't work on WebExtension porting yet.

Also, to make it easier for users (I have no idea if the move to WebExtensions would break autoupdate or no, as with changing permissions) and developers alike (less work to deal with on the Firefox front). If we were to go full WebExtension, I would prefer if it were implemented at the same time as my autoupdate code.

**Comment by Jibodeah** [comment]
I note that it is being reported as 'compatible with multiprocess' now. Has anyone tested that it actually works with multiprocess? (I'll try to remember to do so at some point but no promises)

![BetterPonymotes compatible with multiprocess](https://cloud.githubusercontent.com/assets/1408692/22411814/db7ef668-e69f-11e6-8181-228f1fed1e41.png)

**Comment by Rothera** [comment]
As I recall, @Shugabuga tried to fix it from the Jetpack manifest, but I package my own install.rdf file so that didn't actually do anything. I added the required directive some time ago but never committed it.

Apparently it works? I don't know either.

**Comment by Shugabuga** [comment]
Hmm.
I haven't tested it recently, but the multiprocess manifest test I did when I pushed that PR didn't have any issues. I suppose that the current versions should work unless there was a change recently in Firefox. I don't know as I only use Firefox if I'm desperate.

I know I didn't do anything to do it, as I haven't touched BPM's code since last year (I'm lazy).

**Comment by Jibodeah** [comment]
Alright I'm running multiprocess now and all seems well. Emotes show up, search works, conversion outside of reddit works. Seems fine on all grounds. So I'mma close this. Seems to be working.

(all by other addons, even the ones blocking me from being on multiprocess normally because they're not marked as compatible seem to work too... Maybe I just won't turn this off...)
