### ISSUE TITLE
/catleaves emote is not converted to GIF

### ISSUE THREAD

**Issue by hithroc** [Rothera/bpm#42]
`[](/catleaves)` is an APNG and is not converted to GIF in BPM, thus it's not animated on platforms that do not support APNG (like older versions of Chrome and Electron-based apps, like Discord)

**Comment by hithroc** [comment]
Not relevant anymore.

**Comment by Rothera** [comment]
Oh is that what it was.

This was on my todo list and I couldn't remember why.
